services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: projects_node
    container_name: projects_node
    restart: unless-stopped
    ports:
    - 4010:4010
    environment:
#      TZ: Asia/Seoul
      POSTGRES_USER: handalab
      POSTGRES_PASSWORD: handalab
      POSTGRES_HOST: postgres
      POSTGRES_DB: projects
      POSTGRES_PORT: 5432
    command: npm run dev2 # 주석 처리 시 production mode
    depends_on:
    - postgres
    volumes:
    - ./node:/usr/src/app

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    image: projects_postgres
    container_name: projects_postgres
    ports:
    - 5433:5432
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_DB=projects
      - POSTGRES_USER=handalab
      - POSTGRES_PASSWORD=handalab
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./nsk_postgres/data:/var/lib/postgresql/data